name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 2.2.1
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  # Plugin for parsing html
  html: 0.15.4

  # Plugins for parsing css
  csslib: ^1.0.0

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: 2.0.5

  # Plugins for rendering the <video> tag.
  video_player: 2.8.3
  chewie: 1.7.5

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^3.0.4

  # Plugins for rendering the <audio> tag.
  chewie_audio: 1.5.0

  # Plugins for rendering the <svg> tag.
  flutter_svg: 1.1.6

  # Plugin for rendering MathML
  flutter_math_fork: 0.7.2

  # plugin for firstWhereOrNull extension on lists
  collection: 1.18.0

  # plugin to convert integers to numerals
  numerus: ^2.2.0

  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.3.0
  flutter_test:
    sdk: flutter

flutter:
